# Generated by Django 4.0.4 on 2022-05-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integral',
            options={'managed': True},
        ),
    ]
