# Generated by Django 4.0.4 on 2022-05-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrais', '0002_alter_integral_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integral',
            options={'managed': False},
        ),
    ]
